spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: false
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: info